import { Box, Chip, Paper, Stack, Typography } from '@mui/material';
import { ArrowForward, EventAvailableOutlined, PeopleOutline, PaymentsOutlined } from '@mui/icons-material';
import { useAuth } from '../../context/AuthContext';

export default function DashboardPage() {
  const { user } = useAuth(); const admin = user.role === 'ADMIN';
  const items = admin ? [['Employees', 'Manage your people directory', <PeopleOutline />], ['Attendance', 'See presence across the team', <EventAvailableOutlined />], ['Payroll', 'Keep compensation records current', <PaymentsOutlined />]] : [['Profile', 'Keep your work details current', <PeopleOutline />], ['Attendance', 'Stay on top of your workday', <EventAvailableOutlined />], ['Payroll', 'Review your latest payslips', <PaymentsOutlined />]];
  return <Stack spacing={5}><Box><Chip label={admin ? 'ADMIN WORKSPACE' : 'EMPLOYEE WORKSPACE'} size="small" sx={{ bgcolor: '#e7e1d6', mb: 2, fontWeight: 700, letterSpacing: '.08em' }} /><Typography variant="h2" sx={{ fontSize: { xs: '2.5rem', md: '4rem' }, mb: 1 }}>Good morning, {user.email?.split('@')[0]}.</Typography><Typography color="text.secondary" fontSize="1.1rem">Your Dayflow workspace is ready for the next part of the day.</Typography></Box><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' }, gap: 2 }}>{items.map(([title, copy, icon]) => <Paper key={title} sx={{ p: 3, border: '1px solid #e4ded4', transition: 'transform .2s, box-shadow .2s', '&:hover': { transform: 'translateY(-4px)', boxShadow: '0 14px 30px rgba(13,27,42,.08)' } }}><Stack direction="row" justifyContent="space-between" alignItems="start"><Box sx={{ p: 1, bgcolor: '#f1e9dd', color: 'secondary.main', borderRadius: 2 }}>{icon}</Box><ArrowForward sx={{ color: 'text.secondary' }} /></Stack><Typography variant="h6" sx={{ mt: 5, mb: 1 }}>{title}</Typography><Typography color="text.secondary">{copy}</Typography></Paper>)}</Box><Paper sx={{ p: 3, bgcolor: 'primary.main', color: '#fffaf0' }}><Typography variant="h6">Your connected workspace</Typography><Typography sx={{ mt: 1, color: '#b7c6ca' }}>Phase 1 is connected to the Spring Boot API foundation. Feature pages will appear here as each service is added.</Typography></Paper></Stack>;
}
