import { useEffect, useState } from 'react';
import { Alert, Box, Button, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { toast } from 'react-toastify';
import { applyLeave, getMyLeaves } from '../../services/leaveService';
import { getApiMessage } from '../../services/api';
import LoadingSpinner from '../../components/common/LoadingSpinner';
import ErrorMessage from '../../components/common/ErrorMessage';
import EmptyState from '../../components/common/EmptyState';
import StatusChip from '../../components/common/StatusChip';
import PageControls from '../../components/common/PageControls';

const initialForm = { leaveType: 'PAID', startDate: '', endDate: '', remarks: '' };
export default function Leave() {
  const [form, setForm] = useState(initialForm); const [page, setPage] = useState(null); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  const load = async (pageNumber = 0) => { setLoading(true); setError(''); try { const response = await getMyLeaves({ page: pageNumber, size: 10 }); setPage(response.data); } catch (requestError) { setError(getApiMessage(requestError, 'Unable to load leave requests.')); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); if (!form.leaveType || !form.startDate || !form.endDate) return setError('Leave type and both dates are required.'); if (form.endDate < form.startDate) return setError('End date cannot be before start date.'); setSubmitting(true); setError(''); try { const response = await applyLeave(form); toast.success(response.message || 'Leave request submitted.'); setForm(initialForm); await load(); } catch (requestError) { toast.error(getApiMessage(requestError, 'Unable to submit leave request.')); } finally { setSubmitting(false); } };
  if (loading) return <LoadingSpinner label="Loading leave requests..." />; if (error && !page) return <ErrorMessage message={error} onRetry={load} />;
  return <Stack spacing={3}><Box><Typography variant="h2" sx={{ fontSize: { xs: '2.5rem', md: '4rem' } }}>Leave</Typography><Typography color="text.secondary">Request time away and track every decision.</Typography></Box><Paper sx={{ p: { xs: 2, sm: 3 }, border: '1px solid #e4ded4' }}><Typography variant="h5" sx={{ mb: 2 }}>Apply for leave</Typography><Box component="form" onSubmit={submit} sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)' }, gap: 2 }}><TextField select label="Leave type" value={form.leaveType} onChange={(event) => setForm({ ...form, leaveType: event.target.value })}>{['PAID', 'SICK', 'UNPAID'].map((type) => <MenuItem key={type} value={type}>{type}</MenuItem>)}</TextField><Box /><TextField type="date" label="Start date" InputLabelProps={{ shrink: true }} value={form.startDate} onChange={(event) => setForm({ ...form, startDate: event.target.value })} /><TextField type="date" label="End date" InputLabelProps={{ shrink: true }} value={form.endDate} onChange={(event) => setForm({ ...form, endDate: event.target.value })} /><TextField label="Remarks" multiline minRows={3} value={form.remarks} onChange={(event) => setForm({ ...form, remarks: event.target.value })} sx={{ gridColumn: { sm: '1 / -1' } }} />{error && <Alert severity="error" sx={{ gridColumn: { sm: '1 / -1' } }}>{error}</Alert>}<Button type="submit" variant="contained" disabled={submitting} sx={{ justifySelf: 'start' }}>{submitting ? 'Submitting...' : 'Submit request'}</Button></Box></Paper><Paper sx={{ p: 2, border: '1px solid #e4ded4' }}><Typography variant="h5" sx={{ p: 1, mb: 1 }}>Request history</Typography><TableContainer><Table sx={{ minWidth: 700 }}><TableHead><TableRow>{['Type', 'Dates', 'Days', 'Remarks', 'Status', 'Admin comment'].map((heading) => <TableCell key={heading}>{heading}</TableCell>)}</TableRow></TableHead><TableBody>{page?.content?.length ? page.content.map((request) => <TableRow key={request.id}><TableCell>{request.leaveType}</TableCell><TableCell>{request.startDate} to {request.endDate}</TableCell><TableCell>{request.numberOfDays}</TableCell><TableCell>{request.remarks || '—'}</TableCell><TableCell><StatusChip status={request.status} /></TableCell><TableCell>{request.adminComment || '—'}</TableCell></TableRow>) : <TableRow><TableCell colSpan={6}><EmptyState>You haven&apos;t submitted any leave requests yet.</EmptyState></TableCell></TableRow>}</TableBody></Table></TableContainer><PageControls page={page} onChange={load} /></Paper></Stack>;
}
